// Emit the drop-in SEED PACK for db/core/schema.sql from the consolidated
// projection (entities) + pages IA (pages/sections/redirects) + governance facts.
//
// Output: output/seed/
//   entities.json, pages.json, page_sections.json, redirects.json,
//   governance_facts.json  — the data, for JSON consumers.
//   load.sql               — idempotent upserts: drop into a FRESH Postgres that
//                            has db/core/schema.sql applied and the CMS is populated.
//
// entities = the content atoms (projection entities of every type EXCEPT `page`;
// pages live in the IA store, not the atom store). Read-only synced (editable=false).
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const OUT = path.join(root, 'output/seed');
fs.mkdirSync(OUT, { recursive: true });

const projection = JSON.parse(fs.readFileSync(path.join(root, 'output/cms-projection/projection.json'), 'utf8'));
const pagesDoc = JSON.parse(fs.readFileSync(path.join(root, 'output/cms-projection/pages.json'), 'utf8'));
const lock = JSON.parse(fs.readFileSync(path.join(root, 'governance/canonical-facts.json'), 'utf8'));

// ── entities (atoms; drop `page` type) ──
const TITLE_KEYS = ['title', 'name', 'question', 'canonical_wording', 'label'];
function entityFrom(e) {
  const data = {};
  const provenance = {};
  const srcCount = {};
  for (const [f, { value, source }] of Object.entries(e.fields)) {
    data[f] = value;
    provenance[f] = source;
    srcCount[source] = (srcCount[source] || 0) + 1;
  }
  const source = Object.entries(srcCount).sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;
  const slug = e.canonicalKey.split(':').slice(1).join(':');
  let title = null;
  for (const k of TITLE_KEYS) if (typeof data[k] === 'string') { title = data[k]; break; }
  if (!title && data.profile?.title) title = data.profile.title;
  return { entity_type: e.entityType, canonical_key: e.canonicalKey, slug, title, data, provenance, source, editable: false };
}
const entities = projection.entities.filter((e) => e.entityType !== 'page').map(entityFrom);

// ── pages + sections ──
const pages = pagesDoc.pages.map((p) => ({
  route: p.route, file_group: p.file_group, sort_order: p.sort_order, cluster: p.cluster,
  page_type: p.page_type, template: p.template, visual_mode: p.visual_mode, hub_route: p.hub_route,
  title: p.title, h1: p.h1, seo: p.seo, status: 'published',
}));
const sections = [];
for (const p of pagesDoc.pages) {
  p.sections.forEach((s, i) =>
    sections.push({ route: p.route, sort_order: i + 1, section_type: s.type, variant: s.variant,
      content: s.content ?? {}, entity_refs: s.entity_refs ?? [], asset_refs: s.asset_refs ?? [] }),
  );
}
const redirects = (pagesDoc.redirects || []).map((r) => ({ from_path: r.from, to_path: r.to, code: r.code ?? 301 }));

// ── assets (media registry from the SSOT image map; console-editable image swaps) ──
// Optional: skipped if the extract has not been built (data/releases/assets/assets.json).
let assets = [];
try {
  const assetDoc = JSON.parse(fs.readFileSync(path.join(root, 'data/releases/assets/assets.json'), 'utf8'));
  assets = (assetDoc.rows || []).map((a) => ({
    key: a.key,
    kind: a.kind || 'image',
    url: a.url,
    alt: a.alt ?? null,
    meta: {
      title: a.title ?? null, caption: a.caption ?? null, group: a.group ?? null,
      source_field: a.source_field ?? null, source_category: a.source_category ?? null,
      recommended_pages: a.recommended_pages ?? [], link: a.link ?? null,
    },
  }));
} catch { /* asset extract optional (manual, committed) */ }

// ── governance facts (flatten adjudicated_facts + forbidden_values) ──
const facts = [];
for (const [k, v] of Object.entries(lock.adjudicated_facts)) facts.push({ key: k, value: v });
facts.push({ key: 'forbidden_values', value: lock.forbidden_values });

// ── write JSON ──
const write = (name, obj) => fs.writeFileSync(path.join(OUT, name), JSON.stringify(obj, null, 2) + '\n');
write('entities.json', entities);
write('pages.json', pages);
write('page_sections.json', sections);
write('redirects.json', redirects);
write('governance_facts.json', facts);
write('assets.json', assets);

// ── load.sql (idempotent) ──
const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => `'${JSON.stringify(v ?? {}).replace(/'/g, "''")}'::jsonb`;
const arr = (a) => (a && a.length ? `ARRAY[${a.map((x) => q(x)).join(',')}]::text[]` : `'{}'::text[]`);

let sql = `-- output/seed/load.sql — generated by scripts/build-seed.mjs. Idempotent.
-- Prereq: db/core/schema.sql applied to a fresh database. Then:  psql <db> -f output/seed/load.sql
BEGIN;
-- Refresh regenerates ONLY synced sections; console-edited rows (editable=true) are
-- the jvto_cms edit master and must survive an upstream reload.
DELETE FROM page_sections WHERE editable IS NOT TRUE;

`;

sql += '-- governance_facts\n';
for (const f of facts)
  sql += `INSERT INTO governance_facts (key, value) VALUES (${q(f.key)}, ${j(f.value)}) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;\n`;

sql += '\n-- entities\n';
for (const e of entities)
  sql += `INSERT INTO entities (entity_type, canonical_key, slug, title, data, provenance, source, editable) VALUES (${q(e.entity_type)}, ${q(e.canonical_key)}, ${q(e.slug)}, ${q(e.title)}, ${j(e.data)}, ${j(e.provenance)}, ${q(e.source)}, ${e.editable}) ON CONFLICT (canonical_key) DO UPDATE SET data = EXCLUDED.data, provenance = EXCLUDED.provenance, title = EXCLUDED.title, source = EXCLUDED.source, updated_at = now();\n`;

sql += '\n-- assets (media registry; operator image swaps set editable=true and survive reloads)\n';
for (const a of assets)
  sql += `INSERT INTO assets (key, kind, url, alt, meta, editable) VALUES (${q(a.key)}, ${q(a.kind)}, ${q(a.url)}, ${q(a.alt)}, ${j(a.meta)}, false) ON CONFLICT (key) DO UPDATE SET kind = EXCLUDED.kind, url = EXCLUDED.url, alt = EXCLUDED.alt, meta = EXCLUDED.meta WHERE assets.editable IS NOT TRUE;\n`;
sql += '\n-- prune synced assets removed from the seed (editable=true operator swaps survive)\n';
sql += `DELETE FROM assets WHERE editable IS NOT TRUE AND key <> ALL(${arr(assets.map((a) => a.key))});\n`;

sql += '\n-- pages\n';
for (const p of pages)
  sql += `INSERT INTO pages (route, file_group, sort_order, cluster, page_type, template, visual_mode, hub_route, title, h1, seo, status, editable) VALUES (${q(p.route)}, ${q(p.file_group)}, ${p.sort_order}, ${q(p.cluster)}, ${q(p.page_type)}, ${q(p.template)}, ${q(p.visual_mode)}, ${q(p.hub_route)}, ${q(p.title)}, ${q(p.h1)}, ${j(p.seo)}, ${q(p.status)}, false) ON CONFLICT (route) DO UPDATE SET file_group = EXCLUDED.file_group, sort_order = EXCLUDED.sort_order, cluster = EXCLUDED.cluster, page_type = EXCLUDED.page_type, template = EXCLUDED.template, visual_mode = EXCLUDED.visual_mode, hub_route = EXCLUDED.hub_route, title = EXCLUDED.title, h1 = EXCLUDED.h1, seo = EXCLUDED.seo WHERE pages.editable IS NOT TRUE;\n`;

// Prune synced pages whose route left the IA (e.g. a slug rename: /destinations/bromo
// -> /destinations/mount-bromo). Without this the stale page lingers and — because the
// resolver returns a page before ever checking redirects (src/resolvePage.ts) — it
// SHADOWS the short->long redirect. Console-authored pages (editable=true) are preserved;
// page_sections cascade on delete (schema.sql: ON DELETE CASCADE).
sql += '\n-- prune pages whose route left the seed (renames / removals)\n';
sql += `DELETE FROM pages WHERE editable IS NOT TRUE AND route <> ALL(${arr(pages.map((p) => p.route))});\n`;

sql += '\n-- redirects\n';
for (const r of redirects)
  sql += `INSERT INTO redirects (from_path, to_path, code) VALUES (${q(r.from_path)}, ${q(r.to_path)}, ${r.code}) ON CONFLICT (from_path) DO UPDATE SET to_path = EXCLUDED.to_path, code = EXCLUDED.code;\n`;

// Prune synced redirects removed from the IA (redirects carry no editable flag —
// they are wholly seed-owned, so any row not in the seed is stale).
sql += '\n-- prune redirects no longer in the seed\n';
sql += `DELETE FROM redirects WHERE from_path <> ALL(${arr(redirects.map((r) => r.from_path))});\n`;

sql += '\n-- page_sections (page_id resolved by route)\n';
for (const s of sections)
  sql += `INSERT INTO page_sections (page_id, sort_order, section_type, variant, content, entity_refs, asset_refs, editable) SELECT p.id, ${s.sort_order}, ${q(s.section_type)}, ${q(s.variant)}, ${j(s.content)}, ${arr(s.entity_refs)}, ${arr(s.asset_refs)}, false FROM pages p WHERE p.route = ${q(s.route)} ON CONFLICT (page_id, sort_order) DO UPDATE SET section_type = EXCLUDED.section_type, variant = EXCLUDED.variant, content = EXCLUDED.content, entity_refs = EXCLUDED.entity_refs, asset_refs = EXCLUDED.asset_refs WHERE page_sections.editable IS NOT TRUE;\n`;

sql += '\nCOMMIT;\n';
fs.writeFileSync(path.join(OUT, 'load.sql'), sql);

// ── _manifest.json (deterministic; consumed by jvto-web's manifest-gated sync) ──
// generated_at is sourced from the projection (never a wall clock) so re-runs are byte-identical.
const entityKeys = new Set(entities.map((e) => e.canonical_key));
const danglingRefs = [];
for (const s of sections)
  for (const ref of s.entity_refs) if (!entityKeys.has(ref)) danglingRefs.push({ route: s.route, ref });
const routesWithBody = new Set(sections.filter((s) => s.section_type === 'page_content').map((s) => s.route));
const isFullyRendered = (p) => routesWithBody.has(p.route) || Boolean(p.seo && p.seo.description);
const fullyRendered = pages.filter(isFullyRendered).map((p) => p.route).sort();
const scaffoldOnly = pages.filter((p) => !isFullyRendered(p)).map((p) => p.route).sort();
const byType = {};
for (const e of entities) byType[e.entity_type] = (byType[e.entity_type] || 0) + 1;

const gates = {
  projection_blocking_conflicts: projection.counts?.blockingConflicts ?? 0,
  projection_warnings: projection.counts?.warnings ?? 0,
  dangling_entity_refs: danglingRefs.length,
  governance_facts_present: facts.length > 0,
};
// The seed is consumable iff the projection is conflict-free, no entity_ref dangles,
// and the facts lock shipped. facts_lock is enforced at read-time by the resolver +
// by jvto-web's validate:cms-seed; here we assert the lock is PRESENT and structurally clean.
const validation =
  gates.projection_blocking_conflicts === 0 &&
  gates.dangling_entity_refs === 0 &&
  gates.governance_facts_present
    ? 'pass'
    : 'fail';

const manifest = {
  bundle: 'cms-seed',
  schema_version: 'cms-seed/v1',
  source: 'jvto-unified-cms-bootstrap',
  generated_at: projection.generatedAt ?? projection.generated_at ?? null,
  files: ['entities.json', 'pages.json', 'page_sections.json', 'redirects.json', 'governance_facts.json', 'assets.json', 'load.sql'],
  counts: {
    entities: entities.length,
    entities_by_type: byType,
    pages: pages.length,
    sections: sections.length,
    redirects: redirects.length,
    governance_facts: facts.length,
    assets: assets.length,
    routes_fully_rendered: fullyRendered.length,
    routes_scaffold_only: scaffoldOnly.length,
  },
  routes_scaffold_only: scaffoldOnly, // explicit so consumers keep their own fallback for these
  gates,
  validation,
};
write('_manifest.json', manifest);
if (validation !== 'pass') {
  console.error('build-seed: _manifest validation FAILED', JSON.stringify(gates));
  process.exit(1);
}

console.log(
  `Seed pack → output/seed/: ${entities.length} entities, ${pages.length} pages, ${sections.length} sections, ` +
    `${redirects.length} redirects, ${facts.length} governance_facts, ${assets.length} assets. load.sql ${(sql.length / 1024).toFixed(0)}KB. ` +
    `_manifest: validation=${validation}, fully_rendered=${fullyRendered.length}/${pages.length}, scaffold_only=[${scaffoldOnly.join(', ')}].`,
);
