-- db/jvto-dev/target-schema.sql
-- A FAITHFUL LOCAL DOUBLE of the tables the jvto_cms -> jvto_dev sync writes to,
-- translated from the live jvto-web Prisma schema
--   (/workspace/jvto-itinerary-core/input/jvto-web/schema.prisma).
--
-- Purpose: stand up `jvto_dev_local` so scripts/sync-to-jvto-dev.mjs can be PROVEN
-- offline (the sandbox cannot reach the live DB on :5432). This file emulates only the
-- EXISTING jvto_dev tables in the sync scope (Pages + Org + Assets). The sync script
-- itself creates the additive cms_* layer at run time; it is NOT part of this double.
--
-- Live jvto_dev is Prisma-managed; do NOT apply this file there. It exists purely to
-- reproduce jvto_dev's shape (columns + the UNIQUE keys the sync upserts against) locally.
-- Column types mirror Prisma: BigInt->bigint identity, Json->jsonb, String[]->text[],
-- DateTime @db.Timestamptz(6)->timestamptz, enums->CREATE TYPE.

BEGIN;

-- ── enums ─────────────────────────────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE asset_type AS ENUM ('image', 'video', 'document');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE destination_asset_type AS ENUM ('primary', 'secondary');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── site content / pages / SEO (the sync landing zone) ─────────────────────────
CREATE TABLE IF NOT EXISTS content_pages (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route          text        NOT NULL,
  lang           text        NOT NULL DEFAULT 'en',
  schema_version int         NOT NULL DEFAULT 1,
  seo            jsonb       NOT NULL DEFAULT '{}'::jsonb,
  content        jsonb       NOT NULL,
  is_active      boolean     NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (route, lang)                       -- ← sync upsert key
);
CREATE INDEX IF NOT EXISTS idx_content_pages_route ON content_pages(route);
CREATE INDEX IF NOT EXISTS idx_content_pages_is_active ON content_pages(is_active);

CREATE TABLE IF NOT EXISTS organization_profile (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legal_name          text,
  brand_name          text,
  alternate_name      text,
  founding_date       date,
  description         text,
  price_range         text,
  contact_email       text,
  contact_phone       text,
  available_languages text[]      NOT NULL DEFAULT '{}',
  address_json        jsonb,
  same_as_urls        text[]      NOT NULL DEFAULT '{}',
  website_url         text,
  logo_url            text,
  hero_image_url      text,
  schema_json         jsonb,
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS site_identity (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_name                  text        NOT NULL,
  legal_entity_name           text        NOT NULL,
  official_website_url        text        NOT NULL,
  official_emails             jsonb       NOT NULL DEFAULT '[]'::jsonb,
  official_whatsapp_numbers   jsonb       NOT NULL DEFAULT '[]'::jsonb,
  registration_ids            jsonb       NOT NULL DEFAULT '[]'::jsonb,
  official_payment_accounts   jsonb       NOT NULL DEFAULT '[]'::jsonb,
  maps_listings               jsonb       NOT NULL DEFAULT '[]'::jsonb,
  association_memberships     jsonb       NOT NULL DEFAULT '[]'::jsonb,
  office_address              jsonb                DEFAULT '{}'::jsonb,
  google_business_profile_url text,
  brand_positioning           jsonb                DEFAULT '{}'::jsonb,
  founder                     jsonb                DEFAULT '{}'::jsonb,
  org_schema_json_ld          jsonb,
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now()
);

-- ── typed content stubs (FK targets for asset joins; sync matches them by slug) ─
-- Only the columns the sync reads/needs are modelled; live jvto_dev has many more.
CREATE TABLE IF NOT EXISTS destinations (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            text,
  name            text        NOT NULL,
  slug            varchar(255) UNIQUE,
  short_slug      varchar(100),
  thumbnail_url   text,
  featured_image  text,
  seo_title       text,
  seo_description text,
  schema_json     jsonb,
  published       boolean     NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS packages (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            text UNIQUE,
  name            text        NOT NULL,
  slug            text UNIQUE,
  seo_title       text,
  seo_meta        text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ── media / assets system ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS folders (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id  bigint REFERENCES folders(id),
  name       text        NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_folders_parent_id ON folders(parent_id);

CREATE TABLE IF NOT EXISTS tags_assets (
  id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS assets (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folder_id      bigint      NOT NULL REFERENCES folders(id),
  name           text        NOT NULL,
  caption        text,
  description    text,
  type           asset_type  NOT NULL,
  url            text        NOT NULL,
  file_ext       text,
  size_bytes     bigint,
  size_megabytes numeric(12, 4),
  sha256         text,
  last_verified  timestamptz,
  is_active      boolean     NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_assets_folder_id ON assets(folder_id);
CREATE INDEX IF NOT EXISTS idx_assets_is_active ON assets(is_active);
CREATE INDEX IF NOT EXISTS idx_assets_type ON assets(type);
CREATE INDEX IF NOT EXISTS idx_assets_sha256 ON assets(sha256);

CREATE TABLE IF NOT EXISTS asset_tags (
  asset_id bigint NOT NULL REFERENCES assets(id),
  tag_id   bigint NOT NULL REFERENCES tags_assets(id),
  PRIMARY KEY (asset_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_asset_tags_tag_id ON asset_tags(tag_id);

CREATE TABLE IF NOT EXISTS package_assets (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id bigint      NOT NULL REFERENCES packages(id),
  asset_id   bigint      NOT NULL REFERENCES assets(id),
  is_primary boolean     NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (package_id, asset_id)
);
CREATE INDEX IF NOT EXISTS idx_package_assets_package_id ON package_assets(package_id);
CREATE INDEX IF NOT EXISTS idx_package_assets_asset_id ON package_assets(asset_id);

CREATE TABLE IF NOT EXISTS package_images (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id   bigint REFERENCES packages(id),
  url          text NOT NULL,
  og_image_url text,
  sort_order   int,
  alt_text     text,
  caption      text,
  tags         text,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS destination_assets (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destination_id bigint                 NOT NULL REFERENCES destinations(id),
  asset_id       bigint                 NOT NULL REFERENCES assets(id),
  type           destination_asset_type NOT NULL,
  created_at     timestamptz            NOT NULL DEFAULT now(),
  updated_at     timestamptz            NOT NULL DEFAULT now(),
  UNIQUE (destination_id, asset_id)
);
CREATE INDEX IF NOT EXISTS idx_destination_assets_destination_id ON destination_assets(destination_id);
CREATE INDEX IF NOT EXISTS idx_destination_assets_asset_id ON destination_assets(asset_id);

COMMIT;
